spring.application.name=devworkspace
spring.datasource.url=jdbc:postgresql://localhost:5432/devworkspace_db
spring.datasource.username=postgres
spring.datasource.password=admin
implementation 'org.springframework.boot:spring-boot-starter-security'

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8080